import json
import shutil
import os

notebook_path = "kaggle_sen12_gan_resnet/sen12ms-cr-ts-cloud-removal-gan.ipynb"

# 1. Reset notebook by copying baseline
shutil.copy("kaggle_sen12_eda_unet/sen12ms-cr-ts-cloud-removal-eda-baseline-unet.ipynb", notebook_path)
print("Notebook reset to baseline successfully.")

with open(notebook_path, 'r', encoding='utf-8') as f:
    nb = json.load(f)

# 2. Find the model cell and the training cell
model_cell_idx = -1
train_cell_idx = -1

for idx, cell in enumerate(nb['cells']):
    src = "".join(cell['source']) if isinstance(cell['source'], list) else cell['source']
    if "model = MultiTemporalResUNet" in src:
        model_cell_idx = idx
    if "def train_one_epoch" in src:
        train_cell_idx = idx

print(f"Model Cell Index: {model_cell_idx}")
print(f"Train Cell Index: {train_cell_idx}")

if model_cell_idx == -1 or train_cell_idx == -1:
    print("Error: Could not locate cells!")
    exit(1)

# 3. Update Model Cell (append ResNetDiscriminator definition and initialization)
model_src = nb['cells'][model_cell_idx]['source']
if isinstance(model_src, list):
    model_src = "".join(model_src)

discriminator_code = (
    "\n\n# ==================== GAN & DISCRIMINATOR SETUP ====================\n"
    "import torch.nn.utils.spectral_norm as spectral_norm\n\n"
    "class ResidualBlock(nn.Module):\n"
    "    def __init__(self, in_ch, out_ch, stride=1):\n"
    "        super().__init__()\n"
    "        self.net = nn.Sequential(\n"
    "            spectral_norm(nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)),\n"
    "            nn.BatchNorm2d(out_ch),\n"
    "            nn.ReLU(inplace=True),\n"
    "            spectral_norm(nn.Conv2d(out_ch, out_ch, 3, stride=1, padding=1, bias=False)),\n"
    "            nn.BatchNorm2d(out_ch),\n"
    "        )\n"
    "        self.skip = nn.Sequential(\n"
    "            spectral_norm(nn.Conv2d(in_ch, out_ch, 1, stride=stride, bias=False)),\n"
    "            nn.BatchNorm2d(out_ch)\n"
    "        ) if stride != 1 or in_ch != out_ch else nn.Identity()\n"
    "        self.act = nn.ReLU(inplace=True)\n\n"
    "    def forward(self, x):\n"
    "        return self.act(self.net(x) + self.skip(x))\n\n"
    "class ResNetDiscriminator(nn.Module):\n"
    "    def __init__(self, in_channels=13, base=64):\n"
    "        super().__init__()\n"
    "        self.init_conv = nn.Sequential(\n"
    "            spectral_norm(nn.Conv2d(in_channels, base, 7, stride=2, padding=3, bias=False)),\n"
    "            nn.BatchNorm2d(base),\n"
    "            nn.ReLU(inplace=True),\n"
    "            nn.MaxPool2d(3, stride=2, padding=1)\n"
    "        )\n"
    "        self.layer1 = ResidualBlock(base, base)\n"
    "        self.layer2 = ResidualBlock(base, base*2, stride=2)\n"
    "        self.layer3 = ResidualBlock(base*2, base*4, stride=2)\n"
    "        self.gap = nn.AdaptiveAvgPool2d((1, 1))\n"
    "        self.fc = nn.Linear(base*4, 1)\n\n"
    "    def forward(self, x):\n"
    "        x = self.init_conv(x)\n"
    "        x = self.layer1(x)\n"
    "        x = self.layer2(x)\n"
    "        x = self.layer3(x)\n"
    "        x = self.gap(x)\n"
    "        x = torch.flatten(x, 1)\n"
    "        return self.fc(x)\n\n"
    "# GAN Initialization\n"
    "netD = ResNetDiscriminator(in_channels=13, base=CFG.BASE_CHANNELS).to(DEVICE)\n"
    "print('Discriminator model initialized successfully.')\n"
)

nb['cells'][model_cell_idx]['source'] = [model_src + discriminator_code]
print("Model cell updated.")

# 4. Update Training Cell (replace with GAN adversarial training loop and optimizer initialization)
new_training_source = (
    "def mae(pred, target):\n"
    "    return F.l1_loss(pred, target)\n\n"
    "def masked_mae(pred, target, mask):\n"
    "    diff = torch.abs(pred - target) * mask\n"
    "    return diff.sum() / (mask.sum() * pred.shape[1] + 1e-8)\n\n"
    "def weighted_masked_mae(pred, target, mask, weight):\n"
    "    diff = torch.abs(pred - target) * mask * weight\n"
    "    return diff.sum() / ((mask * weight).sum() * pred.shape[1] + 1e-8)\n\n"
    "def bucket_mae(pred, target, bucket_mask):\n"
    "    diff = torch.abs(pred - target) * bucket_mask\n"
    "    val = diff.sum() / (bucket_mask.sum() * pred.shape[1] + 1e-8)\n"
    "    return torch.where(bucket_mask.sum() > 0, val, torch.tensor(float('nan'), device=pred.device))\n\n"
    "def gradient_mae(pred, target, mask):\n"
    "    dy_pred = torch.abs(pred[:, :, 1:, :] - pred[:, :, :-1, :])\n"
    "    dy_target = torch.abs(target[:, :, 1:, :] - target[:, :, :-1, :])\n"
    "    dx_pred = torch.abs(pred[:, :, :, 1:] - pred[:, :, :, :-1])\n"
    "    dx_target = torch.abs(target[:, :, :, 1:] - target[:, :, :, :-1])\n"
    "    \n"
    "    mask_y = mask[:, :, 1:, :]\n"
    "    mask_x = mask[:, :, :, 1:]\n"
    "    \n"
    "    loss_y = torch.abs(dy_pred - dy_target) * mask_y\n"
    "    loss_x = torch.abs(dx_pred - dx_target) * mask_x\n"
    "    \n"
    "    total_loss = loss_y.sum() / (mask_y.sum() * pred.shape[1] + 1e-8) + loss_x.sum() / (mask_x.sum() * pred.shape[1] + 1e-8)\n"
    "    return total_loss\n\n"
    "def rmse(pred, target):\n"
    "    return torch.sqrt(F.mse_loss(pred, target))\n\n"
    "def psnr(pred, target, max_val=1.0):\n"
    "    mse = F.mse_loss(pred, target)\n"
    "    return 20 * torch.log10(torch.tensor(max_val, device=pred.device)) - 10 * torch.log10(mse + 1e-8)\n\n"
    "def apply_copy_outside_mask(raw_pred, t0, mask):\n"
    "    return raw_pred * mask + t0 * (1.0 - mask)\n\n"
    "def heavy_cloud_weight(mask):\n"
    "    return 1.0 + CFG.HEAVY_LOSS_BOOST * mask + CFG.HEAVY_BINARY_BOOST * (mask >= CFG.HEAVY_PIXEL_THRESHOLD).float()\n\n"
    "def cloud_bucket_masks(mask):\n"
    "    light = (mask > 0.0) & (mask < 0.33)\n"
    "    medium = (mask >= 0.33) & (mask < 0.66)\n"
    "    heavy = (mask >= 0.66)\n"
    "    return light.float(), medium.float(), heavy.float()\n\n"
    "def scalar_or_none(x):\n"
    "    return float(x.detach().cpu()) if not torch.isnan(x) else None\n\n"
    "def evaluate(loader, label=\"val\"):\n"
    "    model.eval()\n"
    "    netD.eval()\n"
    "    metrics = {\n"
    "        \"model_mae\": [], \"model_cloud_mae\": [], \"model_light_cloud_mae\": [],\n"
    "        \"model_medium_cloud_mae\": [], \"model_heavy_cloud_mae\": [],\n"
    "        \"raw_cloud_mae\": [], \"t0_mae\": [], \"t0_cloud_mae\": [],\n"
    "        \"t0_light_cloud_mae\": [], \"t0_medium_cloud_mae\": [], \"t0_heavy_cloud_mae\": [],\n"
    "        \"rmse\": [], \"psnr\": [], \"cloud_fraction\": [], \"heavy_fraction\": []\n"
    "    }\n"
    "    with torch.no_grad():\n"
    "        for batch in loader:\n"
    "            x = batch[\"x\"].to(DEVICE)\n"
    "            y = batch[\"y\"].to(DEVICE)\n"
    "            mask = batch[\"cloud_mask\"].to(DEVICE)\n"
    "            t0 = batch[\"t0\"].to(DEVICE)\n"
    "            \n"
    "            raw = model(x)\n"
    "            pred = apply_copy_outside_mask(raw, t0, mask)\n"
    "            \n"
    "            light_m, medium_m, heavy_m = cloud_bucket_masks(mask)\n"
    "            \n"
    "            metrics[\"model_mae\"].append(float(F.l1_loss(pred, y).cpu()))\n"
    "            metrics[\"model_cloud_mae\"].append(float(masked_mae(pred, y, mask).cpu()))\n"
    "            metrics[\"model_light_cloud_mae\"].append(scalar_or_none(bucket_mae(pred, y, light_m)))\n"
    "            metrics[\"model_medium_cloud_mae\"].append(scalar_or_none(bucket_mae(pred, y, medium_m)))\n"
    "            metrics[\"model_heavy_cloud_mae\"].append(scalar_or_none(bucket_mae(pred, y, heavy_m)))\n"
    "            metrics[\"raw_cloud_mae\"].append(float(masked_mae(raw, y, mask).cpu()))\n"
    "            \n"
    "            metrics[\"t0_mae\"].append(float(F.l1_loss(t0, y).cpu()))\n"
    "            metrics[\"t0_cloud_mae\"].append(float(masked_mae(t0, y, mask).cpu()))\n"
    "            metrics[\"t0_light_cloud_mae\"].append(scalar_or_none(bucket_mae(t0, y, light_m)))\n"
    "            metrics[\"t0_medium_cloud_mae\"].append(scalar_or_none(bucket_mae(t0, y, medium_m)))\n"
    "            metrics[\"t0_heavy_cloud_mae\"].append(scalar_or_none(bucket_mae(t0, y, heavy_m)))\n"
    "            \n"
    "            metrics[\"rmse\"].append(float(rmse(pred, y).cpu()))\n"
    "            metrics[\"psnr\"].append(float(psnr(pred, y).cpu()))\n"
    "            metrics[\"cloud_fraction\"].append(float(mask.mean().cpu()))\n"
    "            metrics[\"heavy_fraction\"].append(float(heavy_m.mean().cpu()))\n"
    "            \n"
    "    res = {}\n"
    "    for k, vals in metrics.items():\n"
    "        clean = [v for v in vals if v is not None]\n"
    "        res[k] = float(np.mean(clean)) if clean else 0.0\n"
    "    return res\n\n"
    "def train_one_epoch(loader, epoch, total_epochs):\n"
    "    model.train()\n"
    "    netD.train()\n"
    "    losses = []\n"
    "    d_losses = []\n"
    "    heavy_losses = []\n"
    "    iterator = tqdm(loader, desc=f\"epoch {epoch:03d}/{total_epochs:03d}\", leave=True)\n"
    "    for batch in iterator:\n"
    "        x = batch[\"x\"].to(DEVICE)\n"
    "        y = batch[\"y\"].to(DEVICE)\n"
    "        mask = batch[\"cloud_mask\"].to(DEVICE)\n"
    "        t0 = batch[\"t0\"].to(DEVICE)\n"
    "        \n"
    "        # 1. Update Discriminator\n"
    "        optimizerD.zero_grad()\n"
    "        # Real\n"
    "        out_real = netD(y)\n"
    "        loss_D_real = criterion_GAN(out_real, torch.ones_like(out_real))\n"
    "        # Fake\n"
    "        raw = model(x)\n"
    "        pred = apply_copy_outside_mask(raw, t0, mask)\n"
    "        out_fake = netD(pred.detach())\n"
    "        loss_D_fake = criterion_GAN(out_fake, torch.zeros_like(out_fake))\n"
    "        \n"
    "        loss_D = (loss_D_real + loss_D_fake) * 0.5\n"
    "        loss_D.backward()\n"
    "        optimizerD.step()\n"
    "        d_losses.append(float(loss_D.detach().cpu()))\n"
    "        \n"
    "        # 2. Update Generator\n"
    "        optimizer.zero_grad(set_to_none=True)\n"
    "        out_fake_G = netD(pred)\n"
    "        loss_G_adv = criterion_GAN(out_fake_G, torch.ones_like(out_fake_G))\n"
    "        \n"
    "        weight = heavy_cloud_weight(mask)\n"
    "        whole = F.l1_loss(pred, y)\n"
    "        cloud_plain = masked_mae(pred, y, mask)\n"
    "        cloud_weighted = weighted_masked_mae(pred, y, mask, weight)\n"
    "        raw_cloud_weighted = weighted_masked_mae(raw, y, mask, weight)\n"
    "        copy_penalty = masked_mae(pred, t0, 1.0 - mask)\n"
    "        grad = gradient_mae(pred, y, mask)\n"
    "        _, _, heavy_m = cloud_bucket_masks(mask)\n"
    "        heavy_only = bucket_mae(pred, y, heavy_m)\n"
    "        heavy_term = torch.where(torch.isnan(heavy_only), cloud_plain, heavy_only)\n"
    "        \n"
    "        loss = (\n"
    "            0.15 * whole\n"
    "            + 1.15 * cloud_weighted\n"
    "            + 0.20 * raw_cloud_weighted\n"
    "            + 0.25 * copy_penalty\n"
    "            + 0.10 * grad\n"
    "            + 0.15 * heavy_term\n"
    "            + 0.05 * loss_G_adv\n"
    "        )\n"
    "        loss.backward()\n"
    "        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)\n"
    "        optimizer.step()\n"
    "        losses.append(float(loss.detach().cpu()))\n"
    "        heavy_losses.append(0.0 if bool(torch.isnan(heavy_only).detach().cpu()) else float(heavy_only.detach().cpu()))\n"
    "        \n"
    "        iterator.set_postfix(loss_G=np.mean(losses), loss_D=np.mean(d_losses))\n"
    "        \n"
    "    return float(np.mean(losses)), float(np.mean(d_losses)), float(np.mean(heavy_losses))\n\n"
    "def save_training_plot(history_df):\n"
    "    fig, axes = plt.subplots(1, 2, figsize=(14, 5))\n"
    "    axes[0].plot(history_df[\"epoch\"], history_df[\"train_loss\"], marker=\"o\", label=\"train G loss\")\n"
    "    axes[0].plot(history_df[\"epoch\"], history_df[\"train_cloud_loss\"], marker=\"o\", label=\"train D loss\")\n"
    "    axes[0].plot(history_df[\"epoch\"], history_df[\"val_model_mae\"], marker=\"x\", label=\"val model MAE\")\n"
    "    axes[0].set_title(\"Training Loss & Val MAE\")\n"
    "    axes[0].legend()\n"
    "    axes[0].grid(True)\n"
    "    \n"
    "    axes[1].plot(history_df[\"epoch\"], history_df[\"val_model_cloud_mae\"], marker=\"o\", label=\"val cloud MAE\")\n"
    "    axes[1].plot(history_df[\"epoch\"], history_df[\"val_model_heavy_cloud_mae\"], marker=\"x\", label=\"val heavy cloud MAE\")\n"
    "    axes[1].set_title(\"Validation Cloud MAE\")\n"
    "    axes[1].legend()\n"
    "    axes[1].grid(True)\n"
    "    plt.tight_layout()\n"
    "    plt.savefig(CFG.OUT_DIR / \"training_curves.png\", dpi=150)\n"
    "    plt.close()\n\n"
    "# Optimizer, Schedulers and GAN Loss Definitions\n"
    "optimizer = torch.optim.AdamW(model.parameters(), lr=CFG.LR, weight_decay=1e-4)\n"
    "scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=CFG.EPOCHS, eta_min=CFG.LR * 0.1)\n\n"
    "optimizerD = torch.optim.AdamW(netD.parameters(), lr=CFG.LR, weight_decay=1e-4)\n"
    "schedulerD = torch.optim.lr_scheduler.CosineAnnealingLR(optimizerD, T_max=CFG.EPOCHS, eta_min=CFG.LR * 0.1)\n"
    "criterion_GAN = nn.BCEWithLogitsLoss()\n\n"
    "print(\"strategy: hard/soft copy outside mask; spectral-normalized ResNet-18 GAN; heavy-cloud oversampling\")\n\n"
    "if CFG.RUN_TRAINING:\n"
    "    history = []\n"
    "    best_cloud_mae = float(\"inf\")\n"
    "    \n"
    "    for epoch in range(1, CFG.EPOCHS + 1):\n"
    "        train_loss, train_d_loss, train_heavy_loss = train_one_epoch(train_loader, epoch, CFG.EPOCHS)\n"
    "        val_metrics = evaluate(val_loader, label=\"val\")\n"
    "        \n"
    "        log_row = {\n"
    "            \"epoch\": epoch,\n"
    "            \"train_loss\": train_loss,\n"
    "            \"train_cloud_loss\": train_d_loss,\n"
    "            \"train_heavy_loss\": train_heavy_loss,\n"
    "            \"lr\": optimizer.param_groups[0][\"lr\"],\n"
    "        }\n"
    "        log_row.update(val_metrics)\n"
    "        history.append(log_row)\n"
    "        \n"
    "        # Print metrics\n"
    "        print(f\"Epoch {epoch:02d} | Train G: {train_loss:.5f} | Train D: {train_d_loss:.5f} | Val Cloud MAE: {val_metrics['val_model_cloud_mae']:.5f} | PSNR: {val_metrics['psnr']:.2f} dB\")\n"
    "        \n"
    "        # Checkpoint\n"
    "        if val_metrics[\"val_model_cloud_mae\"] < best_cloud_mae:\n"
    "            best_cloud_mae = val_metrics[\"val_model_cloud_mae\"]\n"
    "            torch.save(model.state_dict(), CFG.OUT_DIR / \"best_multitemporal_resunet_hardmask.pth\")\n"
    "            torch.save(netD.state_dict(), CFG.OUT_DIR / \"best_resnet_discriminator.pth\")\n"
    "            print(f\"  ==> Saved best model weights with cloud MAE {best_cloud_mae:.6f}\")\n"
    "            \n"
    "        torch.save(model.state_dict(), CFG.OUT_DIR / \"last_multitemporal_resunet_hardmask.pth\")\n"
    "        \n"
    "        # Step schedulers\n"
    "        scheduler.step()\n"
    "        schedulerD.step()\n"
    "        \n"
    "        # Save history periodically\n"
    "        history_df = pd.DataFrame(history)\n"
    "        history_df.to_csv(CFG.OUT_DIR / \"training_history.csv\", index=False)\n"
    "        save_training_plot(history_df)\n"
)

nb['cells'][train_cell_idx]['source'] = [new_training_source]
print("Training cell updated.")

# 5. Save the rebuilt notebook
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(nb, f, indent=1)

print("Rebuilding GAN notebook completed successfully.")
